### ISSUE TITLE
How to integrate with ROS

### ISSUE THREAD

**Issue by epshteinmatthew** [tonykolomeytsev/youbot_devcontainer#1]
I saw in your readme that it is possible to integrate the docker environment with ROS. How would I go about this?

**Comment by tonykolomeytsev** [comment]
Hello @epshteinmatthew! Maybe I went too far when I wrote “it’s easy.” Since it's been two years since the code was published, I don't really remember the context. But anyway, I can say for sure that to integrate youbot library with ROS you will have to write your own wrapper in C++. 

The wrapper can be a simple ROS node into which the library from the robot is imported and which launches some actions in response to commands from topics.

There are several ways to do this:

### The first way

If you run ROS applications on a robot inside Docker, you can build your own ROS Docker image using artifacts from my [Dockerfile](https://github.com/tonykolomeytsev/youbot_devcontainer/blob/master/docker/Dockerfile) using multistage build.

### The second way

If you run ROS as is on your robot, just install all things from my [Dockerfile](https://github.com/tonykolomeytsev/youbot_devcontainer/blob/master/docker/Dockerfile) to your system. Then some hacky hack with the youbot library to get yor wrapper ROS node done.

I don't know your level of knowledge. If necessary, I can explain some points in more detail. Unfortunately, if you're looking for a ready-made Python wrapper for ROS, it doesn't exist yet :(

**Comment by epshteinmatthew** [comment]
Hi, thanks for answering. I ended up going about something similar to the first way, and I have a docker image with the youbot ROS wrapper installed on my system now.
